pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\maven:/workspace'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
