pipeline:
  identifier: Build_kirankadapa_simple_java_maven_app_1736250054208
  name: Build simple-java-maven-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: kirankadapa/simple-java-maven-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: maven
                  name: maven
                  spec:
                    command: mvn -B -DskipTests clean package
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
